// flow-typed signature: 48041d78852d50089b68a6f71e6f5888
// flow-typed version: <<STUB>>/babel-preset-stage-2_v^6.18.0/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-preset-stage-2'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-preset-stage-2' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-preset-stage-2/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-preset-stage-2/lib/index.js' {
  declare module.exports: $Exports<'babel-preset-stage-2/lib/index'>;
}
