// flow-typed signature: ee803f7c8aa0017c83139f568b99db6e
// flow-typed version: <<STUB>>/redux-actions_v^1.2.0/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   'redux-actions'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'redux-actions' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'redux-actions/dist/redux-actions' {
  declare module.exports: any;
}

declare module 'redux-actions/dist/redux-actions.min' {
  declare module.exports: any;
}

declare module 'redux-actions/es/combineActions' {
  declare module.exports: any;
}

declare module 'redux-actions/es/createAction' {
  declare module.exports: any;
}

declare module 'redux-actions/es/createActions' {
  declare module.exports: any;
}

declare module 'redux-actions/es/handleAction' {
  declare module.exports: any;
}

declare module 'redux-actions/es/handleActions' {
  declare module.exports: any;
}

declare module 'redux-actions/es/index' {
  declare module.exports: any;
}

declare module 'redux-actions/es/ownKeys' {
  declare module.exports: any;
}

declare module 'redux-actions/lib/combineActions' {
  declare module.exports: any;
}

declare module 'redux-actions/lib/createAction' {
  declare module.exports: any;
}

declare module 'redux-actions/lib/createActions' {
  declare module.exports: any;
}

declare module 'redux-actions/lib/handleAction' {
  declare module.exports: any;
}

declare module 'redux-actions/lib/handleActions' {
  declare module.exports: any;
}

declare module 'redux-actions/lib/index' {
  declare module.exports: any;
}

declare module 'redux-actions/lib/ownKeys' {
  declare module.exports: any;
}

// Filename aliases
declare module 'redux-actions/dist/redux-actions.js' {
  declare module.exports: $Exports<'redux-actions/dist/redux-actions'>;
}
declare module 'redux-actions/dist/redux-actions.min.js' {
  declare module.exports: $Exports<'redux-actions/dist/redux-actions.min'>;
}
declare module 'redux-actions/es/combineActions.js' {
  declare module.exports: $Exports<'redux-actions/es/combineActions'>;
}
declare module 'redux-actions/es/createAction.js' {
  declare module.exports: $Exports<'redux-actions/es/createAction'>;
}
declare module 'redux-actions/es/createActions.js' {
  declare module.exports: $Exports<'redux-actions/es/createActions'>;
}
declare module 'redux-actions/es/handleAction.js' {
  declare module.exports: $Exports<'redux-actions/es/handleAction'>;
}
declare module 'redux-actions/es/handleActions.js' {
  declare module.exports: $Exports<'redux-actions/es/handleActions'>;
}
declare module 'redux-actions/es/index.js' {
  declare module.exports: $Exports<'redux-actions/es/index'>;
}
declare module 'redux-actions/es/ownKeys.js' {
  declare module.exports: $Exports<'redux-actions/es/ownKeys'>;
}
declare module 'redux-actions/lib/combineActions.js' {
  declare module.exports: $Exports<'redux-actions/lib/combineActions'>;
}
declare module 'redux-actions/lib/createAction.js' {
  declare module.exports: $Exports<'redux-actions/lib/createAction'>;
}
declare module 'redux-actions/lib/createActions.js' {
  declare module.exports: $Exports<'redux-actions/lib/createActions'>;
}
declare module 'redux-actions/lib/handleAction.js' {
  declare module.exports: $Exports<'redux-actions/lib/handleAction'>;
}
declare module 'redux-actions/lib/handleActions.js' {
  declare module.exports: $Exports<'redux-actions/lib/handleActions'>;
}
declare module 'redux-actions/lib/index.js' {
  declare module.exports: $Exports<'redux-actions/lib/index'>;
}
declare module 'redux-actions/lib/ownKeys.js' {
  declare module.exports: $Exports<'redux-actions/lib/ownKeys'>;
}
