// flow-typed signature: 1acb60af8a5628efe01b41a4809735cb
// flow-typed version: <<STUB>>/ruta3_v^2.0.1/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   'ruta3'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'ruta3' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'ruta3/pathToRegExp' {
  declare module.exports: any;
}

declare module 'ruta3/test/example' {
  declare module.exports: any;
}

declare module 'ruta3/test/next' {
  declare module.exports: any;
}

declare module 'ruta3/test/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'ruta3/index' {
  declare module.exports: $Exports<'ruta3'>;
}
declare module 'ruta3/index.js' {
  declare module.exports: $Exports<'ruta3'>;
}
declare module 'ruta3/pathToRegExp.js' {
  declare module.exports: $Exports<'ruta3/pathToRegExp'>;
}
declare module 'ruta3/test/example.js' {
  declare module.exports: $Exports<'ruta3/test/example'>;
}
declare module 'ruta3/test/next.js' {
  declare module.exports: $Exports<'ruta3/test/next'>;
}
declare module 'ruta3/test/test.js' {
  declare module.exports: $Exports<'ruta3/test/test'>;
}
